apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: address-web

  template:
    metadata:
      labels:
        app: address-web

    spec:
      containers:
        - name: address-web
          image: address-web:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: DB_HOST
              value: postgres-service

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
